package org.example.ServerCommunication;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: package.proto
// Protobuf Java Version: 4.29.1

public final class ClientPackageClass {
  private ClientPackageClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      ClientPackageClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string strategy = 1;</code>
     * @return The strategy.
     */
    String getStrategy();
    /**
     * <code>string strategy = 1;</code>
     * @return The bytes for strategy.
     */
    com.google.protobuf.ByteString
        getStrategyBytes();

    /**
     * <code>int32 motorASpeed = 2;</code>
     * @return The motorASpeed.
     */
    int getMotorASpeed();

    /**
     * <code>int32 motorBSpeed = 3;</code>
     * @return The motorBSpeed.
     */
    int getMotorBSpeed();

    /**
     * <code>int32 treshold = 4;</code>
     * @return The treshold.
     */
    int getTreshold();

    /**
     * <code>int32 binarisation = 5;</code>
     * @return The binarisation.
     */
    int getBinarisation();

    /**
     * <code>int32 cameraStream = 6;</code>
     * @return The cameraStream.
     */
    int getCameraStream();

    /**
     * <code>int32 flashlightBrightness = 7;</code>
     * @return The flashlightBrightness.
     */
    int getFlashlightBrightness();
  }
  /**
   * Protobuf type {@code ClientPackage}
   */
  public static final class ClientPackage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClientPackage)
      ClientPackageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        ClientPackage.class.getName());
    }
    // Use ClientPackage.newBuilder() to construct.
    private ClientPackage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ClientPackage() {
      strategy_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientPackageClass.internal_static_ClientPackage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientPackageClass.internal_static_ClientPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientPackage.class, Builder.class);
    }

    public static final int STRATEGY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object strategy_ = "";
    /**
     * <code>string strategy = 1;</code>
     * @return The strategy.
     */
    @Override
    public String getStrategy() {
      Object ref = strategy_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        strategy_ = s;
        return s;
      }
    }
    /**
     * <code>string strategy = 1;</code>
     * @return The bytes for strategy.
     */
    @Override
    public com.google.protobuf.ByteString
        getStrategyBytes() {
      Object ref = strategy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        strategy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOTORASPEED_FIELD_NUMBER = 2;
    private int motorASpeed_ = 0;
    /**
     * <code>int32 motorASpeed = 2;</code>
     * @return The motorASpeed.
     */
    @Override
    public int getMotorASpeed() {
      return motorASpeed_;
    }

    public static final int MOTORBSPEED_FIELD_NUMBER = 3;
    private int motorBSpeed_ = 0;
    /**
     * <code>int32 motorBSpeed = 3;</code>
     * @return The motorBSpeed.
     */
    @Override
    public int getMotorBSpeed() {
      return motorBSpeed_;
    }

    public static final int TRESHOLD_FIELD_NUMBER = 4;
    private int treshold_ = 0;
    /**
     * <code>int32 treshold = 4;</code>
     * @return The treshold.
     */
    @Override
    public int getTreshold() {
      return treshold_;
    }

    public static final int BINARISATION_FIELD_NUMBER = 5;
    private int binarisation_ = 0;
    /**
     * <code>int32 binarisation = 5;</code>
     * @return The binarisation.
     */
    @Override
    public int getBinarisation() {
      return binarisation_;
    }

    public static final int CAMERASTREAM_FIELD_NUMBER = 6;
    private int cameraStream_ = 0;
    /**
     * <code>int32 cameraStream = 6;</code>
     * @return The cameraStream.
     */
    @Override
    public int getCameraStream() {
      return cameraStream_;
    }

    public static final int FLASHLIGHTBRIGHTNESS_FIELD_NUMBER = 7;
    private int flashlightBrightness_ = 0;
    /**
     * <code>int32 flashlightBrightness = 7;</code>
     * @return The flashlightBrightness.
     */
    @Override
    public int getFlashlightBrightness() {
      return flashlightBrightness_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(strategy_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, strategy_);
      }
      if (motorASpeed_ != 0) {
        output.writeInt32(2, motorASpeed_);
      }
      if (motorBSpeed_ != 0) {
        output.writeInt32(3, motorBSpeed_);
      }
      if (treshold_ != 0) {
        output.writeInt32(4, treshold_);
      }
      if (binarisation_ != 0) {
        output.writeInt32(5, binarisation_);
      }
      if (cameraStream_ != 0) {
        output.writeInt32(6, cameraStream_);
      }
      if (flashlightBrightness_ != 0) {
        output.writeInt32(7, flashlightBrightness_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(strategy_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, strategy_);
      }
      if (motorASpeed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, motorASpeed_);
      }
      if (motorBSpeed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, motorBSpeed_);
      }
      if (treshold_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, treshold_);
      }
      if (binarisation_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, binarisation_);
      }
      if (cameraStream_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, cameraStream_);
      }
      if (flashlightBrightness_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, flashlightBrightness_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClientPackage)) {
        return super.equals(obj);
      }
      ClientPackage other = (ClientPackage) obj;

      if (!getStrategy()
          .equals(other.getStrategy())) return false;
      if (getMotorASpeed()
          != other.getMotorASpeed()) return false;
      if (getMotorBSpeed()
          != other.getMotorBSpeed()) return false;
      if (getTreshold()
          != other.getTreshold()) return false;
      if (getBinarisation()
          != other.getBinarisation()) return false;
      if (getCameraStream()
          != other.getCameraStream()) return false;
      if (getFlashlightBrightness()
          != other.getFlashlightBrightness()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STRATEGY_FIELD_NUMBER;
      hash = (53 * hash) + getStrategy().hashCode();
      hash = (37 * hash) + MOTORASPEED_FIELD_NUMBER;
      hash = (53 * hash) + getMotorASpeed();
      hash = (37 * hash) + MOTORBSPEED_FIELD_NUMBER;
      hash = (53 * hash) + getMotorBSpeed();
      hash = (37 * hash) + TRESHOLD_FIELD_NUMBER;
      hash = (53 * hash) + getTreshold();
      hash = (37 * hash) + BINARISATION_FIELD_NUMBER;
      hash = (53 * hash) + getBinarisation();
      hash = (37 * hash) + CAMERASTREAM_FIELD_NUMBER;
      hash = (53 * hash) + getCameraStream();
      hash = (37 * hash) + FLASHLIGHTBRIGHTNESS_FIELD_NUMBER;
      hash = (53 * hash) + getFlashlightBrightness();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClientPackage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientPackage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ClientPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ClientPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ClientPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ClientPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClientPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientPackage)
        ClientPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientPackageClass.internal_static_ClientPackage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientPackageClass.internal_static_ClientPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientPackage.class, Builder.class);
      }

      // Construct using ClientPackageClass.ClientPackage.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        strategy_ = "";
        motorASpeed_ = 0;
        motorBSpeed_ = 0;
        treshold_ = 0;
        binarisation_ = 0;
        cameraStream_ = 0;
        flashlightBrightness_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientPackageClass.internal_static_ClientPackage_descriptor;
      }

      @Override
      public ClientPackage getDefaultInstanceForType() {
        return ClientPackage.getDefaultInstance();
      }

      @Override
      public ClientPackage build() {
        ClientPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ClientPackage buildPartial() {
        ClientPackage result = new ClientPackage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ClientPackage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.strategy_ = strategy_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.motorASpeed_ = motorASpeed_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.motorBSpeed_ = motorBSpeed_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.treshold_ = treshold_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.binarisation_ = binarisation_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.cameraStream_ = cameraStream_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.flashlightBrightness_ = flashlightBrightness_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientPackage) {
          return mergeFrom((ClientPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientPackage other) {
        if (other == ClientPackage.getDefaultInstance()) return this;
        if (!other.getStrategy().isEmpty()) {
          strategy_ = other.strategy_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getMotorASpeed() != 0) {
          setMotorASpeed(other.getMotorASpeed());
        }
        if (other.getMotorBSpeed() != 0) {
          setMotorBSpeed(other.getMotorBSpeed());
        }
        if (other.getTreshold() != 0) {
          setTreshold(other.getTreshold());
        }
        if (other.getBinarisation() != 0) {
          setBinarisation(other.getBinarisation());
        }
        if (other.getCameraStream() != 0) {
          setCameraStream(other.getCameraStream());
        }
        if (other.getFlashlightBrightness() != 0) {
          setFlashlightBrightness(other.getFlashlightBrightness());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                strategy_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                motorASpeed_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                motorBSpeed_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                treshold_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                binarisation_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                cameraStream_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                flashlightBrightness_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object strategy_ = "";
      /**
       * <code>string strategy = 1;</code>
       * @return The strategy.
       */
      public String getStrategy() {
        Object ref = strategy_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          strategy_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string strategy = 1;</code>
       * @return The bytes for strategy.
       */
      public com.google.protobuf.ByteString
          getStrategyBytes() {
        Object ref = strategy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          strategy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string strategy = 1;</code>
       * @param value The strategy to set.
       * @return This builder for chaining.
       */
      public Builder setStrategy(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        strategy_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string strategy = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStrategy() {
        strategy_ = getDefaultInstance().getStrategy();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string strategy = 1;</code>
       * @param value The bytes for strategy to set.
       * @return This builder for chaining.
       */
      public Builder setStrategyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        strategy_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int motorASpeed_ ;
      /**
       * <code>int32 motorASpeed = 2;</code>
       * @return The motorASpeed.
       */
      @Override
      public int getMotorASpeed() {
        return motorASpeed_;
      }
      /**
       * <code>int32 motorASpeed = 2;</code>
       * @param value The motorASpeed to set.
       * @return This builder for chaining.
       */
      public Builder setMotorASpeed(int value) {

        motorASpeed_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 motorASpeed = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMotorASpeed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        motorASpeed_ = 0;
        onChanged();
        return this;
      }

      private int motorBSpeed_ ;
      /**
       * <code>int32 motorBSpeed = 3;</code>
       * @return The motorBSpeed.
       */
      @Override
      public int getMotorBSpeed() {
        return motorBSpeed_;
      }
      /**
       * <code>int32 motorBSpeed = 3;</code>
       * @param value The motorBSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setMotorBSpeed(int value) {

        motorBSpeed_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 motorBSpeed = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMotorBSpeed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        motorBSpeed_ = 0;
        onChanged();
        return this;
      }

      private int treshold_ ;
      /**
       * <code>int32 treshold = 4;</code>
       * @return The treshold.
       */
      @Override
      public int getTreshold() {
        return treshold_;
      }
      /**
       * <code>int32 treshold = 4;</code>
       * @param value The treshold to set.
       * @return This builder for chaining.
       */
      public Builder setTreshold(int value) {

        treshold_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 treshold = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTreshold() {
        bitField0_ = (bitField0_ & ~0x00000008);
        treshold_ = 0;
        onChanged();
        return this;
      }

      private int binarisation_ ;
      /**
       * <code>int32 binarisation = 5;</code>
       * @return The binarisation.
       */
      @Override
      public int getBinarisation() {
        return binarisation_;
      }
      /**
       * <code>int32 binarisation = 5;</code>
       * @param value The binarisation to set.
       * @return This builder for chaining.
       */
      public Builder setBinarisation(int value) {

        binarisation_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 binarisation = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBinarisation() {
        bitField0_ = (bitField0_ & ~0x00000010);
        binarisation_ = 0;
        onChanged();
        return this;
      }

      private int cameraStream_ ;
      /**
       * <code>int32 cameraStream = 6;</code>
       * @return The cameraStream.
       */
      @Override
      public int getCameraStream() {
        return cameraStream_;
      }
      /**
       * <code>int32 cameraStream = 6;</code>
       * @param value The cameraStream to set.
       * @return This builder for chaining.
       */
      public Builder setCameraStream(int value) {

        cameraStream_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cameraStream = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCameraStream() {
        bitField0_ = (bitField0_ & ~0x00000020);
        cameraStream_ = 0;
        onChanged();
        return this;
      }

      private int flashlightBrightness_ ;
      /**
       * <code>int32 flashlightBrightness = 7;</code>
       * @return The flashlightBrightness.
       */
      @Override
      public int getFlashlightBrightness() {
        return flashlightBrightness_;
      }
      /**
       * <code>int32 flashlightBrightness = 7;</code>
       * @param value The flashlightBrightness to set.
       * @return This builder for chaining.
       */
      public Builder setFlashlightBrightness(int value) {

        flashlightBrightness_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int32 flashlightBrightness = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlashlightBrightness() {
        bitField0_ = (bitField0_ & ~0x00000040);
        flashlightBrightness_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClientPackage)
    }

    // @@protoc_insertion_point(class_scope:ClientPackage)
    private static final ClientPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientPackage();
    }

    public static ClientPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientPackage>
        PARSER = new com.google.protobuf.AbstractParser<ClientPackage>() {
      @Override
      public ClientPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ClientPackage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClientPackage> getParserForType() {
      return PARSER;
    }

    @Override
    public ClientPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rpackage.proto\"\247\001\n\rClientPackage\022\020\n\010str" +
      "ategy\030\001 \001(\t\022\023\n\013motorASpeed\030\002 \001(\005\022\023\n\013moto" +
      "rBSpeed\030\003 \001(\005\022\020\n\010treshold\030\004 \001(\005\022\024\n\014binar" +
      "isation\030\005 \001(\005\022\024\n\014cameraStream\030\006 \001(\005\022\034\n\024f" +
      "lashlightBrightness\030\007 \001(\005B\024B\022ClientPacka" +
      "geClassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ClientPackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientPackage_descriptor,
        new String[] { "Strategy", "MotorASpeed", "MotorBSpeed", "Treshold", "Binarisation", "CameraStream", "FlashlightBrightness", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
